### Analysing & Cleaning Data

In [1]:
import pandas as pd

In [2]:
import re

def smart_parse_dates(s):

    s = s.astype(str)
    out = pd.Series(pd.NaT, index=s.index)
    patterns = [
        (r'^\d{4}-\d{2}-\d{2}$',        '%Y-%m-%d'),
        (r'^\d{2}/\d{2}/\d{4}$',        '%m/%d/%Y'),
        (r'^\d{2}-\d{2}-\d{4}$',        '%d-%m-%Y'),
        (r'^\d{2} [A-Za-z]{3} \d{4}$',  '%d %b %Y'),
        (r'^\d{4}/\d{2}/\d{2}$',        '%Y/%m/%d'),
    ]
    for pat, fmt in patterns:
        mask = s.str.match(pat, na=False)
        out.loc[mask] = pd.to_datetime(s[mask], format=fmt, errors='coerce')
    return out

In [3]:
cal = pd.read_csv(r"C:\Users\Ranu Gupta\OneDrive\Desktop\Project 1- Sales Analytics'\Messy dataset\Calender.csv")

In [4]:
cal.head(5)

         date
0  1997-01-01
1  1997-01-02
2  1997-01-03
3  1997-01-04
4  1997-01-05

In [5]:
cal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    730 non-null    object
dtypes: object(1)
memory usage: 5.8+ KB

In [6]:
cal["date"].isna().sum()

np.int64(0)

In [7]:
cal["date"].min()

'1997-01-01'

In [8]:
cal["date"].max()

'1998-12-31'

In [9]:
cal["date"] = smart_parse_dates(cal["date"])

In [10]:
cal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    730 non-null    datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 5.8 KB

In [11]:
cal[cal["date"].duplicated()]

Empty DataFrame
Columns: [date]
Index: []

In [12]:
cal.to_csv("cleaned_calender.csv", index = False)

In [13]:
cust = pd.read_csv(r"C:\Users\Ranu Gupta\OneDrive\Desktop\Project 1- Sales Analytics'\Messy dataset\Customers.csv")

In [14]:
cust.head(5)

,customer_id,customer_acct_num,first_name,last_name,customer_address,customer_city,customer_state_province,customer_postal_code,customer_country,birthdate,marital_status,yearly_income,gender,total_children,num_children_at_home,education,acct_open_date,member_card,occupation,homeowner
0,1,ACC0000001,Robert,Wright,6598 Cedar Ln,NEWARK,NJ,50394,USA,NaN,S,$130K - $150K,M,1,1,High School,11/14/1991,Normal,Management,yes
1,2,ACC0000002,DANIEL,Lopez,1652 1st St,Tucson,AZ,31676,USA,1959-06-10,Married,NaN,M,2,2,High School,10/23/1998,BRONZE,pROFESSIONAL,Y
2,3,ACC0000003,PAUL,Harris,4624 Maple Ave,Raleigh,NC,21977,USA,1958-01-07,S,$150K +,f,1,0,GRADUATE DEGREE,1992/11/11,Normal,Clerical,N
3,4,ACC0000004,Jennifer,Gonzalez,1280 Cedar Ln,Houston,TX,68205,USA,03 Jul 1980,S,"$50,000-$70,000",M,0,0,Bachelor's Degree,1998/10/12,Normal,Professional,Y
4,5,ACC0000005,Paul,Clark,7672 Pine Rd,Phoenix,AZ,32143,United States,08 Nov 1960,M,$30K - $50K,F,2,0,Bachelor's Degree,10 Nov 1990,Silver,NaN,Y

In [15]:
cust.shape

(10281, 20)

In [16]:
cust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10281 entries, 0 to 10280
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              10281 non-null  int64
 1   customer_acct_num        10281 non-null  object
 2   first_name               10281 non-null  object
 3   last_name                10281 non-null  object
 4   customer_address         10281 non-null  object
 5   customer_city            10281 non-null  object
 6   customer_state_province  10281 non-null  object
 7   customer_postal_code     9670 non-null   object
 8   customer_country         10281 non-null  object
 9   birthdate                9766 non-null   object
 10  marital_status           10097 non-null  object
 11  yearly_income            9237 non-null   object
 12  gender                   10281 non-null  object
 13  total_children           10281 non-null  int64
 14  num_children_at_home     10281 non-null  int64
 15  education                10281 non-null  object
 16  acct_open_date           10176 non-null  object
 17  member_card              10281 non-null  object
 18  occupation               9440 non-null   object
 19  homeowner                10281 non-null  object
dtypes: int64(3), object(17)
memory usage: 1.6+ MB

In [17]:
cust["customer_id"].duplicated().sum()

np.int64(0)

In [18]:
cust.describe().round(2)

       customer_id  total_children  num_children_at_home
count     10281.00        10281.00              10281.00
mean       5141.00            1.51                  0.76
std        2968.01            1.40                  1.06
min           1.00            0.00                  0.00
25%        2571.00            0.00                  0.00
50%        5141.00            1.00                  0.00
75%        7711.00            2.00                  1.00
max       10281.00            5.00                  5.00

In [19]:
# identifying the text inconsistency
for col in cust.columns:
    if cust[col].nunique() < 20:
        print(col)
        print(cust[col])

# Taken nunique less than 20 because wanted to exclude the primary key and other columns that are meant to be unique like customer_id, customer_acct_num, first_name, last_name

customer_country
0                  USA
1                  USA
2                  USA
3                  USA
4        United States
             ...
10276           Canada
10277              USA
10278           mexico
10279              USA
10280              USA
Name: customer_country, Length: 10281, dtype: object
marital_status
0              S
1        Married
2              S
3              S
4              M
          ...
10276     single
10277          M
10278          M
10279          S
10280          S
Name: marital_status, Length: 10281, dtype: object
gender
0        M
1        M
2        f
3        M
4        F
        ..
10276    F
10277    M
10278    M
10279    m
10280    M
Name: gender, Length: 10281, dtype: object
total_children
0        1
1        2
2        1
3        0
4        2
        ..
10276    3
10277    0
10278    2
10279    0
10280    4
Name: total_children, Length: 10281, dtype: int64
num_children_at_home
0        1
1        2
2        0
3        0
4        0
        ..
10276    1
10277    0
10278    1
10279    0
10280    3
Name: num_children_at_home, Length: 10281, dtype: int64
member_card
0        Normal
1        BRONZE
2        Normal
3        Normal
4        Silver
          ...
10276    Bronze
10277    Bronze
10278    Bronze
10279    Silver
10280      Gold
Name: member_card, Length: 10281, dtype: object
homeowner
0        yes
1          Y
2          N
3          Y
4          Y
        ...
10276    yes
10277      Y
10278      Y
10279      Y
10280      1
Name: homeowner, Length: 10281, dtype: object

In [20]:
for col in ["customer_country", "marital_status", "gender", "member_card", "homeowner"]:
    cust[col] = cust[col].str.strip().str.title()

In [21]:
cust["customer_country"].unique()

array(['Usa', 'United States', 'México', 'Mexico', 'U.S.A.', 'Canada',
       'Can.', 'Us'], dtype=object)

In [22]:
cust["customer_country"].replace({"Usa" : "USA", "United States" : "USA", "México" : "Mexico", "U.S.A." : "USA", "Can." : "Canada", "Us": "USA"}, inplace= True)

C:\Users\Ranu Gupta\AppData\Local\Temp\ipykernel_10640\1745418974.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cust["customer_country"].replace({"Usa" : "USA", "United States" : "USA", "México" : "Mexico", "U.S.A." : "USA", "Can." : "Canada", "Us": "USA"}, inplace= True)

In [23]:
cust["customer_country"].unique()

array(['USA', 'Mexico', 'Canada'], dtype=object)

In [24]:
cust["marital_status"].unique()

array(['S', 'Married', 'M', nan, 'Single'], dtype=object)

In [25]:
cust["marital_status"].replace({"S" : "Single", "M" : "Married"}, inplace = True)

C:\Users\Ranu Gupta\AppData\Local\Temp\ipykernel_10640\1119333940.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cust["marital_status"].replace({"S" : "Single", "M" : "Married"}, inplace = True)

In [26]:
cust["marital_status"].unique()

array(['Single', 'Married', nan], dtype=object)

In [27]:
cust["gender"].unique()

array(['M', 'F', 'Male', 'Female'], dtype=object)

In [28]:
cust["gender"].replace({"M" : "Male", "F" : "Female"}, inplace= True)

C:\Users\Ranu Gupta\AppData\Local\Temp\ipykernel_10640\1601360058.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cust["gender"].replace({"M" : "Male", "F" : "Female"}, inplace= True)

In [29]:
cust["gender"].unique()

array(['Male', 'Female'], dtype=object)

In [30]:
cust["member_card"].unique()

array(['Normal', 'Bronze', 'Silver', 'Gold'], dtype=object)

In [31]:
cust[cust["member_card"] == "Normal"].shape

(2559, 20)

In [32]:
cust["homeowner"].unique()

array(['Yes', 'Y', 'N', 'No', '1', '0'], dtype=object)

In [33]:
cust["homeowner"].replace({"Y" : "Yes", "N":"No", "0" : "No", "1" : "Yes" }, inplace= True)

C:\Users\Ranu Gupta\AppData\Local\Temp\ipykernel_10640\4065843236.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cust["homeowner"].replace({"Y" : "Yes", "N":"No", "0" : "No", "1" : "Yes" }, inplace= True)

In [34]:
cust["homeowner"].unique()

array(['Yes', 'No'], dtype=object)

In [35]:
cust.head(5)

,customer_id,customer_acct_num,first_name,last_name,customer_address,customer_city,customer_state_province,customer_postal_code,customer_country,birthdate,marital_status,yearly_income,gender,total_children,num_children_at_home,education,acct_open_date,member_card,occupation,homeowner
0,1,ACC0000001,Robert,Wright,6598 Cedar Ln,NEWARK,NJ,50394,USA,NaN,Single,$130K - $150K,Male,1,1,High School,11/14/1991,Normal,Management,Yes
1,2,ACC0000002,DANIEL,Lopez,1652 1st St,Tucson,AZ,31676,USA,1959-06-10,Married,NaN,Male,2,2,High School,10/23/1998,Bronze,pROFESSIONAL,Yes
2,3,ACC0000003,PAUL,Harris,4624 Maple Ave,Raleigh,NC,21977,USA,1958-01-07,Single,$150K +,Female,1,0,GRADUATE DEGREE,1992/11/11,Normal,Clerical,No
3,4,ACC0000004,Jennifer,Gonzalez,1280 Cedar Ln,Houston,TX,68205,USA,03 Jul 1980,Single,"$50,000-$70,000",Male,0,0,Bachelor's Degree,1998/10/12,Normal,Professional,Yes
4,5,ACC0000005,Paul,Clark,7672 Pine Rd,Phoenix,AZ,32143,USA,08 Nov 1960,Married,$30K - $50K,Female,2,0,Bachelor's Degree,10 Nov 1990,Silver,NaN,Yes

In [36]:
for col in ["first_name", "last_name", "customer_city", "education", "occupation"]:
    cust[col] = cust[col].str.strip().str.title()

In [37]:
cust.head(5)

,customer_id,customer_acct_num,first_name,last_name,customer_address,customer_city,customer_state_province,customer_postal_code,customer_country,birthdate,marital_status,yearly_income,gender,total_children,num_children_at_home,education,acct_open_date,member_card,occupation,homeowner
0,1,ACC0000001,Robert,Wright,6598 Cedar Ln,Newark,NJ,50394,USA,NaN,Single,$130K - $150K,Male,1,1,High School,11/14/1991,Normal,Management,Yes
1,2,ACC0000002,Daniel,Lopez,1652 1st St,Tucson,AZ,31676,USA,1959-06-10,Married,NaN,Male,2,2,High School,10/23/1998,Bronze,Professional,Yes
2,3,ACC0000003,Paul,Harris,4624 Maple Ave,Raleigh,NC,21977,USA,1958-01-07,Single,$150K +,Female,1,0,Graduate Degree,1992/11/11,Normal,Clerical,No
3,4,ACC0000004,Jennifer,Gonzalez,1280 Cedar Ln,Houston,TX,68205,USA,03 Jul 1980,Single,"$50,000-$70,000",Male,0,0,Bachelor'S Degree,1998/10/12,Normal,Professional,Yes
4,5,ACC0000005,Paul,Clark,7672 Pine Rd,Phoenix,AZ,32143,USA,08 Nov 1960,Married,$30K - $50K,Female,2,0,Bachelor'S Degree,10 Nov 1990,Silver,NaN,Yes

In [38]:
cust["customer_city"].unique()

array(['Newark', 'Tucson', 'Raleigh', 'Houston', 'Phoenix',
       'Indianapolis', 'Cleveland', 'Seattle', 'Hartford', 'Memphis',
       'Tijuana', 'Albuquerque', 'Spokane', 'Puebla', 'Philadelphia',
       'Mexico City', 'Calgary', 'Austin', 'Denver', 'Vancouver',
       'Charlotte', 'Pittsburgh', 'San Diego', 'Los Angeles', 'Portland',
       'Billings', 'Reno', 'Oakland', 'Honolulu', 'Salt Lake City',
       'Miami', 'Milwaukee', 'New York', 'Minneapolis', 'Orlando',
       'Winnipeg', 'Cheyenne', 'Sacramento', 'Boise', 'Buffalo',
       'Monterrey', 'San Jose', 'San Antonio', 'Chicago', 'Atlanta',
       'Tacoma', 'Columbus', 'Montreal', 'Guadalajara', 'Dallas',
       'Toronto', 'Fresno', 'Colorado Springs', 'Nashville', 'Boston',
       'Ottawa', 'Detroit'], dtype=object)

In [39]:
cust["customer_state_province"].unique()

array(['NJ', 'AZ', 'NC', 'TX', 'IN', 'OH', 'WA', 'CT', 'TN', 'BC', 'NM',
       'PUE', 'PA', 'DF', 'AB', 'CO', 'bc', 'CA', 'OR', 'MT', 'tx', 'NV',
       'HI', 'UT', 'FL', 'wi', 'NY', 'MN', 'MB', 'WY', 'ID', 'NL', 'il',
       'GA', 'nc', 'ca', 'ny', 'QC', 'JAL', 'nm', 'ON', 'fl', 'WI', 'wy',
       'az', 'hi', 'pa', 'IL', 'MA', 'ut', 'MI', 'oh', 'on', 'wa', 'mb',
       'co', 'jal', 'tn', 'df', 'ct', 'mt', 'pue', 'ab', 'qc', 'nl', 'mi',
       'nv', 'mn', 'nj', 'or', 'id', 'in', 'ga', 'ma'], dtype=object)

In [40]:
cust["customer_state_province"] = cust["customer_state_province"].str.strip().str.upper()

In [41]:
cust["customer_state_province"].unique()

array(['NJ', 'AZ', 'NC', 'TX', 'IN', 'OH', 'WA', 'CT', 'TN', 'BC', 'NM',
       'PUE', 'PA', 'DF', 'AB', 'CO', 'CA', 'OR', 'MT', 'NV', 'HI', 'UT',
       'FL', 'WI', 'NY', 'MN', 'MB', 'WY', 'ID', 'NL', 'IL', 'GA', 'QC',
       'JAL', 'ON', 'MA', 'MI'], dtype=object)

In [42]:
cust["education"].unique()

array(['High School', 'Graduate Degree', "Bachelor'S Degree",
       'Some College', 'Partial High School'], dtype=object)

In [43]:
cust["occupation"].unique()

array(['Management', 'Professional', 'Clerical', nan, 'Skilled Manual',
       'Manual'], dtype=object)

In [44]:
cust.head(5)

,customer_id,customer_acct_num,first_name,last_name,customer_address,customer_city,customer_state_province,customer_postal_code,customer_country,birthdate,marital_status,yearly_income,gender,total_children,num_children_at_home,education,acct_open_date,member_card,occupation,homeowner
0,1,ACC0000001,Robert,Wright,6598 Cedar Ln,Newark,NJ,50394,USA,NaN,Single,$130K - $150K,Male,1,1,High School,11/14/1991,Normal,Management,Yes
1,2,ACC0000002,Daniel,Lopez,1652 1st St,Tucson,AZ,31676,USA,1959-06-10,Married,NaN,Male,2,2,High School,10/23/1998,Bronze,Professional,Yes
2,3,ACC0000003,Paul,Harris,4624 Maple Ave,Raleigh,NC,21977,USA,1958-01-07,Single,$150K +,Female,1,0,Graduate Degree,1992/11/11,Normal,Clerical,No
3,4,ACC0000004,Jennifer,Gonzalez,1280 Cedar Ln,Houston,TX,68205,USA,03 Jul 1980,Single,"$50,000-$70,000",Male,0,0,Bachelor'S Degree,1998/10/12,Normal,Professional,Yes
4,5,ACC0000005,Paul,Clark,7672 Pine Rd,Phoenix,AZ,32143,USA,08 Nov 1960,Married,$30K - $50K,Female,2,0,Bachelor'S Degree,10 Nov 1990,Silver,NaN,Yes

In [45]:
cust["yearly_income"].unique()

array(['$130K - $150K', nan, '$150K +', '$50,000-$70,000', '$30K - $50K',
       '130K-150K', '$110K - $130K', '$50K - $70K', '30K-50K',
       '$10K - $30K', '$30,000-$50,000', '$90,000-$110,000',
       '$70K - $90K', '$70,000-$90,000', '$90K - $110K', '50K-70K',
       '90K-110K', '$10,000-$30,000', '70K-90K', '150K+',
       '$110,000-$130,000', '10K-30K', '$150,000 +', '110K-130K',
       '$130,000-$150,000'], dtype=object)

In [46]:
income_map = {
    '$10,000-$30,000': '$10K - $30K',
    '10K-30K': '$10K - $30K',

    '$30,000-$50,000': '$30K - $50K',
    '30K-50K': '$30K - $50K',

    '$50,000-$70,000': '$50K - $70K',
    '50K-70K': '$50K - $70K',

    '$70,000-$90,000': '$70K - $90K',
    '70K-90K': '$70K - $90K',

    '$90,000-$110,000': '$90K - $110K',
    '90K-110K': '$90K - $110K',

    '$110,000-$130,000': '$110K - $130K',
    '110K-130K': '$110K - $130K',

    '$130,000-$150,000': '$130K - $150K',
    '130K-150K': '$130K - $150K',

    '$150,000 +': '$150K+',
    '$150K +': '$150K+',
    '150K+': '$150K+'
}

In [47]:
cust["yearly_income"] = cust["yearly_income"].replace(income_map)

In [48]:
order = [
    '$10K - $30K',
    '$30K - $50K',
    '$50K - $70K',
    '$70K - $90K',
    '$90K - $110K',
    '$110K - $130K',
    '$130K - $150K',
    '$150K+'
]

cust['yearly_income'] = pd.Categorical(
    cust['yearly_income'],
    categories=order,
    ordered=True
)

In [49]:
cust["yearly_income"].unique()

['$130K - $150K', NaN, '$150K+', '$50K - $70K', '$30K - $50K', '$110K - $130K', '$10K - $30K', '$90K - $110K', '$70K - $90K']
Categories (8, object): ['$10K - $30K' < '$30K - $50K' < '$50K - $70K' < '$70K - $90K' < '$90K - $110K' < '$110K - $130K' < '$130K - $150K' < '$150K+']

In [50]:
cust["birthdate"].unique()

array([nan, '1959-06-10', '1958-01-07', ..., '13 Mar 1954', '1955/11/07',
       '29 Dec 1939'], shape=(9370,), dtype=object)

In [51]:
cust["birthdate"] = smart_parse_dates(cust["birthdate"])

In [52]:
cust["birthdate"].unique()

<DatetimeArray>
[                'NaT', '1959-06-10 00:00:00', '1958-01-07 00:00:00',
 '1980-07-03 00:00:00', '1960-11-08 00:00:00', '1968-11-27 00:00:00',
 '1948-03-31 00:00:00', '1956-12-30 00:00:00', '1939-10-01 00:00:00',
 '1947-06-30 00:00:00',
 ...
 '1978-04-14 00:00:00', '1931-11-30 00:00:00', '1977-10-28 00:00:00',
 '1956-12-12 00:00:00', '1949-06-22 00:00:00', '1953-07-25 00:00:00',
 '1968-08-02 00:00:00', '1964-08-02 00:00:00', '1954-03-13 00:00:00',
 '1939-12-29 00:00:00']
Length: 7858, dtype: datetime64[ns]

In [53]:
cust.head(5)

,customer_id,customer_acct_num,first_name,last_name,customer_address,customer_city,customer_state_province,customer_postal_code,customer_country,birthdate,marital_status,yearly_income,gender,total_children,num_children_at_home,education,acct_open_date,member_card,occupation,homeowner
0,1,ACC0000001,Robert,Wright,6598 Cedar Ln,Newark,NJ,50394,USA,NaT,Single,$130K - $150K,Male,1,1,High School,11/14/1991,Normal,Management,Yes
1,2,ACC0000002,Daniel,Lopez,1652 1st St,Tucson,AZ,31676,USA,1959-06-10,Married,NaN,Male,2,2,High School,10/23/1998,Bronze,Professional,Yes
2,3,ACC0000003,Paul,Harris,4624 Maple Ave,Raleigh,NC,21977,USA,1958-01-07,Single,$150K+,Female,1,0,Graduate Degree,1992/11/11,Normal,Clerical,No
3,4,ACC0000004,Jennifer,Gonzalez,1280 Cedar Ln,Houston,TX,68205,USA,1980-07-03,Single,$50K - $70K,Male,0,0,Bachelor'S Degree,1998/10/12,Normal,Professional,Yes
4,5,ACC0000005,Paul,Clark,7672 Pine Rd,Phoenix,AZ,32143,USA,1960-11-08,Married,$30K - $50K,Female,2,0,Bachelor'S Degree,10 Nov 1990,Silver,NaN,Yes

In [54]:
cust.isna().sum()

customer_id                   0
customer_acct_num             0
first_name                    0
last_name                     0
customer_address              0
customer_city                 0
customer_state_province       0
customer_postal_code        611
customer_country              0
birthdate                   515
marital_status              184
yearly_income              1044
gender                        0
total_children                0
num_children_at_home          0
education                     0
acct_open_date              105
member_card                   0
occupation                  841
homeowner                     0
dtype: int64

In [55]:
#No missing values were imputed in this table because the primary key (customer_id) contains no missing values. The missing values are limited to descriptive attributes (such as birth date, yearly income,gender and postal code), and imputing them could introduce inaccurate information and potentially bias the analysis. Therefore, these missing values were retained as NaN

In [56]:
cust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10281 entries, 0 to 10280
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              10281 non-null  int64
 1   customer_acct_num        10281 non-null  object
 2   first_name               10281 non-null  object
 3   last_name                10281 non-null  object
 4   customer_address         10281 non-null  object
 5   customer_city            10281 non-null  object
 6   customer_state_province  10281 non-null  object
 7   customer_postal_code     9670 non-null   object
 8   customer_country         10281 non-null  object
 9   birthdate                9766 non-null   datetime64[ns]
 10  marital_status           10097 non-null  object
 11  yearly_income            9237 non-null   category
 12  gender                   10281 non-null  object
 13  total_children           10281 non-null  int64
 14  num_children_at_home     10281 non-null  int64
 15  education                10281 non-null  object
 16  acct_open_date           10176 non-null  object
 17  member_card              10281 non-null  object
 18  occupation               9440 non-null   object
 19  homeowner                10281 non-null  object
dtypes: category(1), datetime64[ns](1), int64(3), object(15)
memory usage: 1.5+ MB

In [57]:
# changing the  data type of the customer_id to string because not mathematical operations will be performed using the customer_id

cust["customer_id"] = cust["customer_id"].astype(str)

In [58]:
cust["acct_open_date"].unique()

array(['11/14/1991', '10/23/1998', '1992/11/11', ..., '05 Mar 1990',
       '1995/12/02', '1998/01/20'], shape=(7566,), dtype=object)

In [59]:
cust["acct_open_date"] = smart_parse_dates(cust["acct_open_date"])

In [60]:
cust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10281 entries, 0 to 10280
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              10281 non-null  object
 1   customer_acct_num        10281 non-null  object
 2   first_name               10281 non-null  object
 3   last_name                10281 non-null  object
 4   customer_address         10281 non-null  object
 5   customer_city            10281 non-null  object
 6   customer_state_province  10281 non-null  object
 7   customer_postal_code     9670 non-null   object
 8   customer_country         10281 non-null  object
 9   birthdate                9766 non-null   datetime64[ns]
 10  marital_status           10097 non-null  object
 11  yearly_income            9237 non-null   category
 12  gender                   10281 non-null  object
 13  total_children           10281 non-null  int64
 14  num_children_at_home     10281 non-null  int64
 15  education                10281 non-null  object
 16  acct_open_date           10176 non-null  datetime64[ns]
 17  member_card              10281 non-null  object
 18  occupation               9440 non-null   object
 19  homeowner                10281 non-null  object
dtypes: category(1), datetime64[ns](2), int64(2), object(15)
memory usage: 1.5+ MB

In [61]:
cust.to_csv("cleaned Customers.csv", index= False)

In [62]:
pro = pd.read_csv(r"C:\Users\Ranu Gupta\OneDrive\Desktop\Project 1- Sales Analytics'\Messy dataset\Products.csv")

In [63]:
pro.head(5)

,product_id,product_brand,product_name,product_sku,product_retail_price,product_cost,product_weight,recyclable,low_fat
0,1,EcoHarvest,EcoHarvest Extra Crunchy Lotion,E-00001-X,10.53,4.52,1.07,0,0
1,2,BluePeak,BluePeak Fresh Bread,B-00002-M,2.71,NaN,0.83,1,0
2,3,crystal springs,Crystal Springs Jumbo Sausage,CS-00003-V,$10.13,5.75,1.38,1,0
3,4,Natures Best,Natures Best Organic Yogurt,NB-00004-N,3.56,2.39,1.53,1,0
4,5,Silver Creek,Silver Creek Reduced Fat Shampoo,SC-00005-Q,9.61,4.04,0.20,1,0

In [64]:
pro.shape

(1560, 9)

In [65]:
pro.isna().sum()

product_id               0
product_brand            0
product_name             0
product_sku              0
product_retail_price     0
product_cost            53
product_weight          60
recyclable              27
low_fat                 26
dtype: int64

In [66]:
pro.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1560 entries, 0 to 1559
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   product_id            1560 non-null   int64
 1   product_brand         1560 non-null   object
 2   product_name          1560 non-null   object
 3   product_sku           1560 non-null   object
 4   product_retail_price  1560 non-null   object
 5   product_cost          1507 non-null   float64
 6   product_weight        1500 non-null   float64
 7   recyclable            1533 non-null   object
 8   low_fat               1534 non-null   object
dtypes: float64(2), int64(1), object(6)
memory usage: 109.8+ KB

In [67]:
pro["product_sku"].unique()

array(['E-00001-X', 'B-00002-M', 'CS-00003-V', ..., 'NB-01558-V',
       'GH-01559-A', 'SO-01560-K'], shape=(1560,), dtype=object)

In [68]:
pro["product_retail_price"].unique()

array(['10.53', '2.71', '$10.13', '3.56', '9.61', '6.59', '7.1', '2.83',
       '4.64', '5.64', '$4.12', '$5.70', '7.26', '5.8', '4.36', '5.36',
       '6.21', '11.86', '1.74', '7.8', '3.44', '7.19', '4.42', '2.27',
       '8.49', '3.8', '0.68', '13.57', '$8.48', '10.04', '3.09', '3.07',
       '8.77', '2.57', '9.96', '4.6', '8.28', '13.33', '$7.00', '5.43',
       '2.09', '1.97', '2.47', '4.61', '$0.93', '2.56', '1.75', '7.4',
       '10.93', '3.17', '6.63', '7.79', '5.69', '3.37', '$8.14', '6.67',
       '6.98', '7.02', '2.85', '4.73', '2.28', '8.4', '3.9', '2.16',
       '3.97', '2.12', '2.37', '6.35', '5.48', '3.65', '1.14', '14.72',
       '14.63', '11.34', '2.21', '$2.88', '10.79', '10.97', '2.51',
       '11.63', '6.3', '3.14', '3.5', '7.27', '2.98', '4.88', '3.82',
       '3.39', '9.6', '11.31', '3.35', '1.78', '$1.09', '7.41', '2.97',
       '7.21', '2.61', '0.95', '$5.17', '3.99', '3.86', '3.15', '8.05',
       '3.26', '4.5', '5.95', '4.01', '2.81', '2.49', '$7.28', '10.76',
       '12.47', '4.27', '15.73', '2.2', '5.53', '11.56', '7.18', '10.47',
       '7.86', '9.58', '6.22', '8.61', '15.64', '7.49', '3.85', '1.9',
       '1.88', '2.7', '8.52', '7.67', '7.37', '6.48', '8.42', '10.83',
       '10.25', '1.41', '6.07', '3.87', '2.42', '5.19', '2.68', '3.98',
       '10.08', '3.24', '4.44', '5.52', '$5.95', '4.31', '5.12', '3.3',
       '14.77', '9.91', '$1.12', '6.53', '3.63', '5.23', '6.66', '$4.15',
       '3.55', '13.26', '3.73', '1.57', '1.92', '1.83', '8.38', '11.01',
       '5.99', '12.94', '6.2', '4.68', '5.32', '5.11', '7.58', '2.26',
       '$2.74', '8.09', '11.83', '4.2', '0.86', '4.74', '9.44', '6.46',
       '2.74', '6.45', '8.19', '1.33', '10.35', '10.73', '10.78', '$3.19',
       '8.59', '1.55', '3.94', '6.23', '2.1', '12.82', '5.62', '3.77',
       '4.71', '4.28', '2.07', '3.06', '7.17', '2.36', '9.07', '0.74',
       '$1.64', '10.45', '5.38', '5.04', '4.39', '$5.25', '4.06', '3.52',
       '8.21', '4.91', '10.01', '4.24', '$3.69', '11.92', '$1.66', '7.23',
       '$1.61', '2.62', '4.05', '5.26', '2.89', '5.25', '1.7', '1.12',
       '3.78', '2.34', '3.67', '7.42', '5.01', '$5.30', '11.0', '3.2',
       '8.15', '3.84', '9.12', '0.87', '$4.77', '0.66', '3.81', '4.15',
       '7.64', '13.04', '10.56', '$15.86', '5.34', '10.27', '4.57',
       '3.61', '$6.96', '10.88', '8.55', '$10.80', '3.16', '1.17',
       '13.27', '12.18', '6.18', '5.93', '8.44', '3.12', '$8.49', '2.23',
       '1.95', '4.96', '$2.94', '4.21', '9.09', '1.79', '3.25', '9.36',
       '4.78', '3.75', '5.65', '10.65', '6.89', '7.93', '8.91', '7.84',
       '10.96', '13.18', '6.96', '6.65', '5.24', '4.82', '$2.38', '9.97',
       '11.71', '4.0', '0.62', '4.99', '2.6', '3.71', '6.97', '5.02',
       '$4.98', '$2.81', '2.99', '3.92', '2.03', '4.53', '12.71', '4.09',
       '8.69', '1.86', '11.93', '6.17', '1.3', '4.83', '11.07', '3.6',
       '$4.76', '1.52', '0.85', '6.03', '4.98', '2.31', '3.22', '6.4',
       '5.31', '1.47', '8.9', '6.87', '4.51', '0.98', '3.43', '4.92',
       '6.42', '$1.69', '5.79', '8.93', '10.05', '$8.13', '4.97', '2.82',
       '3.7', '5.67', '6.64', '6.73', '10.42', '11.06', '4.72', '11.57',
       '8.65', '8.96', '2.29', '5.13', '7.61', '5.51', '$7.63', '6.75',
       '8.33', '12.8', '3.0', '14.36', '11.62', '11.4', '7.15', '$10.49',
       '4.69', '7.36', '11.33', '5.74', '3.03', '$2.83', '2.92', '1.43',
       '8.27', '13.51', '6.52', '4.89', '10.95', '13.64', '14.58', '5.81',
       '13.75', '8.76', '11.53', '1.65', '$4.88', '6.27', '$4.34', '15.8',
       '1.25', '3.54', '2.06', '$1.87', '1.76', '$7.93', '3.49', '5.63',
       '$13.65', '7.76', '1.03', '8.89', '15.31', '4.41', '5.28', '2.32',
       '4.84', '5.92', '9.23', '1.32', '4.62', '15.21', '4.37', '6.14',
       '5.66', '$4.00', '1.02', '9.57', '14.25', '5.06', '5.71', '8.01',
       '4.45', '7.56', '4.4', '2.14', '$2.23', '10.28', '4.04', '10.75',
       '3.23', '6.88', '4.95', '2.54', '1.89', '5.07', '7.51', '5.57',
       '2.88', '12.3', '0.8', '6.24', '4.77', '6.92', '1.48', '1.96',
       '1.56', '$3.72', '6.85', '7.87', '15.15', '$2.97', '5.41', '7.11',
       '$2.89', '8.46', '2.67', '5.09', '6.08', '2.63', '1.44', '4.08',
       '$4.14', '3.29', '3.48', '1.68', '4.65', '$3.68', '2.95', '$5.42',
       '5.29', '7.54', '6.82', '8.82', '1.8', '2.65', '6.99', '$3.70',
       '0.51', '2.44', '4.79', '4.86', '9.0', '7.25', '5.39', '12.69',
       '6.0', '3.41', '$6.82', '14.46', '4.59', '$2.17', '12.77', '2.39',
       '$12.67', '3.53', '$4.73', '3.05', '3.33', '0.59', '2.18', '$1.08',
       '3.31', '$4.42', '3.58', '$3.20', '10.3', '9.72', '5.5', '7.91',
       '3.89', '$11.41', '8.66', '1.77', '3.28', '3.18', '$4.31', '3.4',
       '$1.74', '$5.73', '10.68', '10.62', '8.53', '6.55', '1.84', '2.69',
       '6.7', '$4.08', '$6.14', '$4.16', '3.76', '4.23', '7.03', '$3.12',
       '14.21', '9.99', '$1.91', '9.74', '0.71', '$11.42', '5.86', '7.88',
       '7.24', '11.03', '$7.84', '9.15', '7.65', '3.51', '10.07', '2.05',
       '6.47', '5.85', '7.53', '14.19', '$2.96', '4.54', '$3.01', '2.4',
       '5.3', '4.58', '6.95', '7.89', '2.46', '3.69', '13.53', '13.21',
       '3.91', '8.85', '10.15', '$2.02', '1.45', '8.1', '7.66', '2.02',
       '11.65', '2.78', '11.59', '10.23', '6.93', '$2.90', '2.72', '4.87',
       '9.31', '1.18', '3.83', '10.41', '2.08', '11.42', '9.51', '1.66',
       '7.99', '3.59', '$5.59', '10.66', '2.73', '$3.83', '7.08', '2.94',
       '9.8', '7.97', '2.3', '4.48', '9.1', '4.43', '4.18', '5.58',
       '12.66', '$2.12', '8.83', '1.67', '1.72', '7.44', '$4.40', '6.16',
       '9.79', '$7.24', '7.55', '5.17', '4.38', '4.3', '$1.10', '$3.73',
       '2.01', '4.52', '2.86', '4.9', '2.45', '3.34', '4.46', '8.23',
       '8.04', '11.54', '4.75', '5.4', '1.21', '15.3', '9.19', '5.2',
       '$7.55', '1.63', '6.72', '2.84', '5.72', '4.25', '$8.87', '2.35',
       '5.18', '5.61', '8.94', '3.57', '1.73', '10.9', '$3.41', '7.38',
       '9.25', '10.49', '3.36', '8.06', '$8.34', '12.73', '3.95', '10.44',
       '10.71', '$3.75', '5.49', '$9.16', '$7.78', '$10.18', '15.1',
       '$6.80', '2.04', '1.81', '5.33', '$2.45', '$4.60', '2.58', '$3.62',
       '$2.75', '8.57', '$3.53', '1.07', '5.08', '$8.61', '2.66', '4.67',
       '$15.01', '$1.36', '9.03', '3.62', '$2.91', '3.93', '11.22',
       '10.94', '4.19', '1.1', '4.56', '4.63', '1.59', '6.34', '2.53',
       '1.34', '$7.37', '9.59', '13.55', '15.67', '10.13', '$2.55',
       '2.17', '4.93', '3.45', '$10.76', '$3.17', '15.82', '6.1', '8.02',
       '8.95', '9.68', '$4.62', '0.83', '7.06', '$1.78', '$8.67', '1.99',
       '9.39', '12.98', '6.74', '5.35', '5.76', '4.8', '2.33', '6.28',
       '4.81', '2.93', '7.94', '8.98', '8.11', '0.57', '7.05', '4.22',
       '$3.23', '8.97', '5.21', '8.24', '$1.65', '2.79', '5.44', '6.11',
       '6.43', '14.01', '9.26', '1.85', '$7.21', '$4.06', '$2.53', '0.89',
       '4.26', '$0.91', '6.84', '11.36', '$3.10', '4.14', '2.77', '6.6',
       '1.58', '4.12', '3.21', '$6.36', '11.89', '11.27', '5.78', '$3.74',
       '4.1', '7.95', '$4.69', '10.38', '2.64', '1.71', '$4.53', '1.87',
       '0.64', '3.32', '$0.69', '10.61', '1.98', '6.86', '$10.03',
       '11.24', '10.58', '4.7', '3.88', '15.45', '10.69', '3.13', '$1.82',
       '6.15', '1.69', '7.04', '$7.40', '13.23', '4.02', '7.39', '1.54',
       '7.0', '9.4', '9.77', '4.07', '5.16', '9.06', '5.42', '8.13',
       '9.22', '14.18', '2.5', '$3.26', '11.95', '4.49', '$4.84', '2.91',
       '9.18', '$3.18', '8.75', '8.6', '11.2', '4.94', '8.07', '1.46',
       '9.66', '11.46', '$3.31', '6.8', '2.75', '$1.63', '1.91', '$6.54',
       '5.03', '12.43', '$5.49', '8.92', '10.8', '13.49', '11.8', '7.92',
       '10.89', '8.87', '12.32', '5.96', '5.0', '3.27', '$3.99', '11.3',
       '9.05', '2.87', '12.12', '$2.82', '9.28', '14.12', '4.32', '7.07',
       '1.2', '6.62', '6.13', '1.38', '4.35', '13.89', '10.92', '9.62',
       '$8.38', '10.2', '9.43', '8.72', '9.24', '9.9', '7.74', '3.47',
       '0.99', '1.31', '13.72', '14.42', '3.96', '$5.21', '$8.46', '2.59',
       '10.54', '4.03', '10.06', '$2.18', '$11.99', '$3.13', '4.13',
       '$4.36', '$4.17', '8.43', '5.56', '$8.52', '3.74', '14.87', '5.73',
       '6.31', '11.38', '11.61', '2.41', '6.04', '7.5', '$9.32', '4.55',
       '11.23', '9.13', '2.22', '7.16', '3.66', '5.59', '8.29', '15.65',
       '9.11', '12.45', '12.19', '$12.14', '0.91', '14.78', '12.5',
       '2.11', '12.33', '$4.89', '$2.31', '$4.46', '8.62', '$12.46',
       '$6.55', '5.14', '$5.45', '10.34', '2.96', '$5.79', '$0.98',
       '6.36', '10.85', '1.53', '$8.43'], dtype=object)

In [69]:
for col in ["product_brand", "product_name", "recyclable", "low_fat"]:
    pro[col] = pro[col].str.strip().str.title()

In [70]:
pro.head(5)

,product_id,product_brand,product_name,product_sku,product_retail_price,product_cost,product_weight,recyclable,low_fat
0,1,Ecoharvest,Ecoharvest Extra Crunchy Lotion,E-00001-X,10.53,4.52,1.07,0,0
1,2,Bluepeak,Bluepeak Fresh Bread,B-00002-M,2.71,NaN,0.83,1,0
2,3,Crystal Springs,Crystal Springs Jumbo Sausage,CS-00003-V,$10.13,5.75,1.38,1,0
3,4,Natures Best,Natures Best Organic Yogurt,NB-00004-N,3.56,2.39,1.53,1,0
4,5,Silver Creek,Silver Creek Reduced Fat Shampoo,SC-00005-Q,9.61,4.04,0.20,1,0

In [71]:
pro["product_retail_price"] =pro["product_retail_price"].str.strip("$")
pro["product_retail_price"] = pd.to_numeric(pro["product_retail_price"], errors="coerce")

In [72]:
pro["product_retail_price"].dtype

dtype('float64')

In [73]:
pro.isna().sum()

product_id               0
product_brand            0
product_name             0
product_sku              0
product_retail_price     0
product_cost            53
product_weight          60
recyclable              27
low_fat                 26
dtype: int64

In [74]:
pro.head(5)

,product_id,product_brand,product_name,product_sku,product_retail_price,product_cost,product_weight,recyclable,low_fat
0,1,Ecoharvest,Ecoharvest Extra Crunchy Lotion,E-00001-X,10.53,4.52,1.07,0,0
1,2,Bluepeak,Bluepeak Fresh Bread,B-00002-M,2.71,NaN,0.83,1,0
2,3,Crystal Springs,Crystal Springs Jumbo Sausage,CS-00003-V,10.13,5.75,1.38,1,0
3,4,Natures Best,Natures Best Organic Yogurt,NB-00004-N,3.56,2.39,1.53,1,0
4,5,Silver Creek,Silver Creek Reduced Fat Shampoo,SC-00005-Q,9.61,4.04,0.20,1,0

In [75]:
pro["recyclable"].unique()

array(['0', '1', 'False', '0.0', 'Y', 'No', 'Yes', '1.0', 'N', nan,
       'True'], dtype=object)

In [76]:
pro["recyclable"].replace({"0" : "No", "1" : "Yes", "False" : "No", "0.0" : "No", "Y" : "Yes", "1.0" : "Yes", "N" : "No", "True" : "Yes"}, inplace= True)

C:\Users\Ranu Gupta\AppData\Local\Temp\ipykernel_10640\3952519131.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pro["recyclable"].replace({"0" : "No", "1" : "Yes", "False" : "No", "0.0" : "No", "Y" : "Yes", "1.0" : "Yes", "N" : "No", "True" : "Yes"}, inplace= True)

In [77]:
pro["low_fat"].unique()

array(['0', 'No', '0.0', '1', 'N', 'False', '1.0', nan, 'Yes', 'Y',
       'True'], dtype=object)

In [78]:
pro["low_fat"].replace({"0" : "No", "0.0" : "No", "1" : "Yes", "N" : "No", "False" : "No", "1.0" : "Yes", "Y" : "Yes", "True" : "Yes"}, inplace = True)

C:\Users\Ranu Gupta\AppData\Local\Temp\ipykernel_10640\65044068.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pro["low_fat"].replace({"0" : "No", "0.0" : "No", "1" : "Yes", "N" : "No", "False" : "No", "1.0" : "Yes", "Y" : "Yes", "True" : "Yes"}, inplace = True)

In [79]:
pro.head(5)

,product_id,product_brand,product_name,product_sku,product_retail_price,product_cost,product_weight,recyclable,low_fat
0,1,Ecoharvest,Ecoharvest Extra Crunchy Lotion,E-00001-X,10.53,4.52,1.07,No,No
1,2,Bluepeak,Bluepeak Fresh Bread,B-00002-M,2.71,NaN,0.83,Yes,No
2,3,Crystal Springs,Crystal Springs Jumbo Sausage,CS-00003-V,10.13,5.75,1.38,Yes,No
3,4,Natures Best,Natures Best Organic Yogurt,NB-00004-N,3.56,2.39,1.53,Yes,No
4,5,Silver Creek,Silver Creek Reduced Fat Shampoo,SC-00005-Q,9.61,4.04,0.20,Yes,No

In [80]:
pro.isna().sum()

product_id               0
product_brand            0
product_name             0
product_sku              0
product_retail_price     0
product_cost            53
product_weight          60
recyclable              27
low_fat                 26
dtype: int64

In [81]:
# repacing missing values in the product_cost and product_weight column with the median, because replacing with mean could be misleading if there are outliners.

pro["product_cost"].fillna(pro["product_cost"].median(), inplace= True)
pro["product_weight"].fillna(pro["product_weight"].median(), inplace= True)

C:\Users\Ranu Gupta\AppData\Local\Temp\ipykernel_10640\1825490235.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pro["product_cost"].fillna(pro["product_cost"].median(), inplace= True)
C:\Users\Ranu Gupta\AppData\Local\Temp\ipykernel_10640\1825490235.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pro["product_weight"].fillna(pro["product_weight"].median(), inplace= True)

In [82]:
pro["recyclable"].fillna(pro["recyclable"].mode()[0], inplace= True)

In [83]:
pro["low_fat"].fillna(pro["low_fat"].mode()[0], inplace = True)

In [84]:
pro.isna().sum()

product_id              0
product_brand           0
product_name            0
product_sku             0
product_retail_price    0
product_cost            0
product_weight          0
recyclable              0
low_fat                 0
dtype: int64

In [85]:
pro.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1560 entries, 0 to 1559
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   product_id            1560 non-null   int64
 1   product_brand         1560 non-null   object
 2   product_name          1560 non-null   object
 3   product_sku           1560 non-null   object
 4   product_retail_price  1560 non-null   float64
 5   product_cost          1560 non-null   float64
 6   product_weight        1560 non-null   float64
 7   recyclable            1560 non-null   object
 8   low_fat               1560 non-null   object
dtypes: float64(3), int64(1), object(5)
memory usage: 109.8+ KB

In [86]:
pro["product_id"] = pro["product_id"].astype(str)

In [87]:
pro.to_csv("cleaned_products.csv", index = False)

In [88]:
reg = pd.read_csv(r"C:\Users\Ranu Gupta\OneDrive\Desktop\Project 1- Sales Analytics'\Messy dataset\Regions.csv")

In [89]:
reg.head(5)

   region_id   sales_district sales_region
0          1      New York NY    Northeast
1          2        Boston MA    Northeast
2          3  Philadelphia PA    Northeast
3          4    Pittsburgh PA    Northeast
4          5       Buffalo NY    Northeast

In [90]:
reg.shape

(109, 3)

In [91]:
reg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   region_id       109 non-null    int64
 1   sales_district  109 non-null    object
 2   sales_region    109 non-null    object
dtypes: int64(1), object(2)
memory usage: 2.7+ KB

In [92]:
for col in ["sales_district", "sales_region"]:
    reg[col] = reg[col].str.strip().str.title()

In [93]:
reg.isna().sum()

region_id         0
sales_district    0
sales_region      0
dtype: int64

In [94]:
reg[reg["region_id"].duplicated()].shape

(0, 3)

In [95]:
reg["region_id"] = reg["region_id"].astype(str)

In [96]:
reg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   region_id       109 non-null    object
 1   sales_district  109 non-null    object
 2   sales_region    109 non-null    object
dtypes: object(3)
memory usage: 2.7+ KB

In [97]:
reg.to_csv("cleaned Regions.csv", index= False)

In [98]:
ret = pd.read_csv(r"C:\Users\Ranu Gupta\OneDrive\Desktop\Project 1- Sales Analytics'\Messy dataset\Returns.csv")

In [99]:
ret.head(5)

   return_date  product_id  store_id  quantity
0   1998-08-27         206         4       3.0
1   1998/08/04        1224         6       3.0
2   1998/12/17         295         5       2.0
3   28-09-1998         231        11       NaN
4  18 Sep 1998         295         8       2.0

In [100]:
ret.shape

(7087, 4)

In [101]:
ret.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7087 entries, 0 to 7086
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   return_date  7010 non-null   object
 1   product_id   7087 non-null   int64
 2   store_id     7087 non-null   int64
 3   quantity     6881 non-null   float64
dtypes: float64(1), int64(2), object(1)
memory usage: 221.6+ KB

In [102]:
ret["return_date"].unique()

array(['1998-08-27', '1998/08/04', '1998/12/17', ..., '1997/08/30',
       '08-05-1998', '02-04-1998'], shape=(3007,), dtype=object)

In [103]:
ret["return_date"] = smart_parse_dates(ret["return_date"])

In [104]:
ret.isna().sum()

return_date     77
product_id       0
store_id         0
quantity       206
dtype: int64

In [105]:
ret[ret["return_date"].isna()]

     return_date  product_id  store_id  quantity
30           NaT         149        17       4.0
86           NaT         535        18       5.0
101          NaT         474        20       3.0
412          NaT         878        13       3.0
501          NaT        1426        14       2.0
...          ...         ...       ...       ...
6715         NaT          80         3       5.0
6926         NaT         910         2       5.0
6966         NaT        1214         9       5.0
7013         NaT          64        11       1.0
7041         NaT         109         2       5.0

[77 rows x 4 columns]

In [106]:
#Missing values in return_date were retained because the true return date could not be determined from the available data. These rows were not removed, as they still contain valuable information such as the returned product, store, and quantity, which can be used for analyses that do not depend on the return date.

In [107]:
ret[ret["quantity"].isna()]

     return_date  product_id  store_id  quantity
3     1998-09-28         231        11       NaN
19    1998-09-14        1545        18       NaN
98    1998-02-05        1583        11       NaN
99    1997-03-23         109        11       NaN
107   1998-11-04         689        11       NaN
...          ...         ...       ...       ...
6843  1997-05-29        1457         2       NaN
6860  1998-07-05         991         9       NaN
7030  1997-04-22         231         9       NaN
7039  1998-07-30         763         6       NaN
7059  1997-03-30        1498        10       NaN

[206 rows x 4 columns]

In [108]:
ret.dropna(subset= "quantity", inplace= True)

In [109]:
# Removed 206 records with missing quantity because the returned quantity is the primary business metric and could not be reliably inferred. These records were unsuitable for quantitative analysis.

In [110]:
ret.isna().sum()

return_date    73
product_id      0
store_id        0
quantity        0
dtype: int64

In [111]:
ret.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6881 entries, 0 to 7086
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   return_date  6808 non-null   datetime64[ns]
 1   product_id   6881 non-null   int64
 2   store_id     6881 non-null   int64
 3   quantity     6881 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(2)
memory usage: 268.8 KB

In [112]:
for col in ["product_id", "store_id"]:
    ret[col] = ret[col].astype(str)

In [113]:
ret.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6881 entries, 0 to 7086
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   return_date  6808 non-null   datetime64[ns]
 1   product_id   6881 non-null   object
 2   store_id     6881 non-null   object
 3   quantity     6881 non-null   float64
dtypes: datetime64[ns](1), float64(1), object(2)
memory usage: 268.8+ KB

In [114]:
ret.to_csv("cleaned Returns.csv", index = False)

In [115]:
sto = pd.read_csv(r"C:\Users\Ranu Gupta\OneDrive\Desktop\Project 1- Sales Analytics'\Messy dataset\Stores.csv")

In [116]:
sto.head(5)

,store_id,region_id,store_type,store_name,store_street_address,store_city,store_state,store_country,store_phone,first_opened_date,last_remodel_date,total_sqft,grocery_sqft
0,1,80,Mid-Size Grocery,ValueGrocer #001 - Edmonton,2885 Hill St,Edmonton,AB,Canada,434.547.6956,1993/02/18,NaN,20931,12981.0
1,2,17,Gourmet Supermarket,GroceryWorld #002 - Raleigh,8157 Maple Dr,Raleigh,NC,United States,333-467-1204,09/01/1986,11/14/1996,26060,19526.0
2,3,39,Deluxe Supermarket,ValueGrocer #003 - San Antonio,9015 2nd Ave,San Antonio,TX,USA,(949) 321-5475,05/21/1987,NaN,60431,41610.0
3,4,4,Supermarket,SuperSave #004 - Pittsburgh,6339 Broadway,Pittsburgh,PA,United States,489-966-1788,1985-02-02,NaN,39837,26463.0
4,5,13,Deluxe Supermarket,FreshMart #005 - Atlanta,2731 Sunset Rd,Atlanta,GA,USA,9744108007,18 May 1994,04/04/1999,51778,42591.0

In [117]:
sto.shape

(24, 13)

In [118]:
sto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   store_id              24 non-null     int64
 1   region_id             24 non-null     int64
 2   store_type            24 non-null     object
 3   store_name            24 non-null     object
 4   store_street_address  24 non-null     object
 5   store_city            24 non-null     object
 6   store_state           24 non-null     object
 7   store_country         24 non-null     object
 8   store_phone           23 non-null     object
 9   first_opened_date     24 non-null     object
 10  last_remodel_date     12 non-null     object
 11  total_sqft            24 non-null     int64
 12  grocery_sqft          21 non-null     float64
dtypes: float64(1), int64(3), object(9)
memory usage: 2.6+ KB

In [119]:
for col in sto.columns:
    if sto[col].nunique() < 10:
        print(col)
        print(sto[col])

store_type
0        Mid-Size Grocery
1     Gourmet Supermarket
2      Deluxe Supermarket
3             Supermarket
4      Deluxe Supermarket
5         Midsize Grocery
6             supermarket
7             SUPERMARKET
8             Supermarket
9     Gourmet Supermarket
10     Deluxe Supermarket
11            SUPERMARKET
12    Gourmet Supermarket
13     Deluxe Supermarket
14       Mid-Size Grocery
15          small grocery
16       Mid-Size Grocery
17     Deluxe Supermarket
18       Mid-Size Grocery
19       Mid-Size Grocery
20    Gourmet Supermarket
21       Mid-Size Grocery
22            SUPERMARKET
23    Gourmet Supermarket
Name: store_type, dtype: object
store_country
0            Canada
1     United States
2               USA
3     United States
4               USA
5               usa
6            U.S.A.
7               USA
8               USA
9                US
10              USA
11              USA
12    UNITED STATES
13              USA
14              USA
15               US
16              USA
17           Canada
18    United States
19              USA
20              USA
21              USA
22              USA
23              usa
Name: store_country, dtype: object

In [120]:
for col in ["store_type","store_name", "store_street_address","store_city", "store_state" , "store_country"]:
    sto[col] = sto[col].str.strip().str.title()

In [121]:
for col in ["store_type","store_city", "store_state" , "store_country"]:
    print(col)
    print(sto[col].unique())

store_type
['Mid-Size Grocery' 'Gourmet Supermarket' 'Deluxe Supermarket'
 'Supermarket' 'Midsize Grocery' 'Small Grocery']
store_city
['Edmonton' 'Raleigh' 'San Antonio' 'Pittsburgh' 'Atlanta' 'Long Beach'
 'Colorado Springs' 'Omaha' 'Detroit' 'Indianapolis' 'Orlando' 'Albany'
 'Des Moines' 'Los Angeles' 'Minneapolis' 'Vancouver' 'Sacramento' 'Tampa'
 'Reno' 'Boulder' 'Memphis']
store_state
['Ab' 'Nc' 'Tx' 'Pa' 'Ga' 'Ca' 'Co' 'Ne' 'Mi' 'In' 'Fl' 'Ny' 'Ia' 'Mn'
 'Bc' 'Nv' 'Tn']
store_country
['Canada' 'United States' 'Usa' 'U.S.A.' 'Us']

In [122]:
sto["store_type"].replace({"Midsize Grocery" : "Mid-Size Grocery"}, inplace= True)

C:\Users\Ranu Gupta\AppData\Local\Temp\ipykernel_10640\2636720906.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sto["store_type"].replace({"Midsize Grocery" : "Mid-Size Grocery"}, inplace= True)

In [123]:
sto["store_type"].unique()

array(['Mid-Size Grocery', 'Gourmet Supermarket', 'Deluxe Supermarket',
       'Supermarket', 'Small Grocery'], dtype=object)

In [124]:
sto["store_type"].value_counts()

store_type
Mid-Size Grocery       7
Supermarket            6
Gourmet Supermarket    5
Deluxe Supermarket     5
Small Grocery          1
Name: count, dtype: int64

In [125]:
sto["store_state"] = sto["store_state"].str.upper()

In [126]:
sto["store_country"].replace({"United States" : "USA", "Usa" : "USA", "U.S.A." :  "USA", "Us" : "USA"}, inplace= True)

C:\Users\Ranu Gupta\AppData\Local\Temp\ipykernel_10640\135790073.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sto["store_country"].replace({"United States" : "USA", "Usa" : "USA", "U.S.A." :  "USA", "Us" : "USA"}, inplace= True)

In [127]:
sto.head(4)

,store_id,region_id,store_type,store_name,store_street_address,store_city,store_state,store_country,store_phone,first_opened_date,last_remodel_date,total_sqft,grocery_sqft
0,1,80,Mid-Size Grocery,Valuegrocer #001 - Edmonton,2885 Hill St,Edmonton,AB,Canada,434.547.6956,1993/02/18,NaN,20931,12981.0
1,2,17,Gourmet Supermarket,Groceryworld #002 - Raleigh,8157 Maple Dr,Raleigh,NC,USA,333-467-1204,09/01/1986,11/14/1996,26060,19526.0
2,3,39,Deluxe Supermarket,Valuegrocer #003 - San Antonio,9015 2Nd Ave,San Antonio,TX,USA,(949) 321-5475,05/21/1987,NaN,60431,41610.0
3,4,4,Supermarket,Supersave #004 - Pittsburgh,6339 Broadway,Pittsburgh,PA,USA,489-966-1788,1985-02-02,NaN,39837,26463.0

In [128]:
sto["first_opened_date"].unique()

array(['1993/02/18', '09/01/1986', '05/21/1987', '1985-02-02',
       '18 May 1994', '1992/12/03', '1993-05-27', '04/21/1994',
       '21 Jun 1990', '10/12/1991', '01 Sep 1986', '1986/05/14',
       '18 Dec 1992', '08/13/1990', '26 Sep 1991', '18 Feb 1997',
       '04-06-1997', '26-07-1997', '1997-09-24', '1997-10-10',
       '17-12-1997', '1997/12/20', '1998/02/02', '04/18/1998'],
      dtype=object)

In [129]:
sto["first_opened_date"] = smart_parse_dates(sto["first_opened_date"])

In [130]:
sto["first_opened_date"].unique()

<DatetimeArray>
['1993-02-18 00:00:00', '1986-09-01 00:00:00', '1987-05-21 00:00:00',
 '1985-02-02 00:00:00', '1994-05-18 00:00:00', '1992-12-03 00:00:00',
 '1993-05-27 00:00:00', '1994-04-21 00:00:00', '1990-06-21 00:00:00',
 '1991-10-12 00:00:00', '1986-05-14 00:00:00', '1992-12-18 00:00:00',
 '1990-08-13 00:00:00', '1991-09-26 00:00:00', '1997-02-18 00:00:00',
 '1997-06-04 00:00:00', '1997-07-26 00:00:00', '1997-09-24 00:00:00',
 '1997-10-10 00:00:00', '1997-12-17 00:00:00', '1997-12-20 00:00:00',
 '1998-02-02 00:00:00', '1998-04-18 00:00:00']
Length: 23, dtype: datetime64[ns]

In [131]:
sto["last_remodel_date"].unique()

array([nan, '11/14/1996', '04/04/1999', '11/17/1997', '25 Sep 1994',
       '1992/11/05', '10/17/1990', '1994/08/11', '17 Feb 1998',
       '05/05/1998', '01 Nov 1998', '19-05-1999', '31 Mar 1999'],
      dtype=object)

In [132]:
sto["last_remodel_date"] = smart_parse_dates(sto["last_remodel_date"])

In [133]:
sto["last_remodel_date"].unique()

<DatetimeArray>
[                'NaT', '1996-11-14 00:00:00', '1999-04-04 00:00:00',
 '1997-11-17 00:00:00', '1994-09-25 00:00:00', '1992-11-05 00:00:00',
 '1990-10-17 00:00:00', '1994-08-11 00:00:00', '1998-02-17 00:00:00',
 '1998-05-05 00:00:00', '1998-11-01 00:00:00', '1999-05-19 00:00:00',
 '1999-03-31 00:00:00']
Length: 13, dtype: datetime64[ns]

In [134]:
sto["store_phone"].unique()

array(['434.547.6956', '333-467-1204', '(949) 321-5475', '489-966-1788',
       '9744108007', '301.564.7335', '(806) 593-7474', nan, '8333363699',
       '5345855203', '(633) 578-8267', '(207) 916-5884', '(783) 780-9447',
       '6436364337', '611-923-3303', '912-272-7736', '468.728.4691',
       '3922252104', '3564243792', '339.383.3513', '533-359-8777',
       '941.264.4577', '(938) 598-1223', '205.972.2493'], dtype=object)

In [135]:
sto["store_phone"] = sto["store_phone"].str.replace(r"\D", "", regex=True)

In [136]:
sto["store_phone"].unique()

array(['4345476956', '3334671204', '9493215475', '4899661788',
       '9744108007', '3015647335', '8065937474', nan, '8333363699',
       '5345855203', '6335788267', '2079165884', '7837809447',
       '6436364337', '6119233303', '9122727736', '4687284691',
       '3922252104', '3564243792', '3393833513', '5333598777',
       '9412644577', '9385981223', '2059722493'], dtype=object)

In [137]:
sto.head(5)

,store_id,region_id,store_type,store_name,store_street_address,store_city,store_state,store_country,store_phone,first_opened_date,last_remodel_date,total_sqft,grocery_sqft
0,1,80,Mid-Size Grocery,Valuegrocer #001 - Edmonton,2885 Hill St,Edmonton,AB,Canada,4345476956,1993-02-18,NaT,20931,12981.0
1,2,17,Gourmet Supermarket,Groceryworld #002 - Raleigh,8157 Maple Dr,Raleigh,NC,USA,3334671204,1986-09-01,1996-11-14,26060,19526.0
2,3,39,Deluxe Supermarket,Valuegrocer #003 - San Antonio,9015 2Nd Ave,San Antonio,TX,USA,9493215475,1987-05-21,NaT,60431,41610.0
3,4,4,Supermarket,Supersave #004 - Pittsburgh,6339 Broadway,Pittsburgh,PA,USA,4899661788,1985-02-02,NaT,39837,26463.0
4,5,13,Deluxe Supermarket,Freshmart #005 - Atlanta,2731 Sunset Rd,Atlanta,GA,USA,9744108007,1994-05-18,1999-04-04,51778,42591.0

In [138]:
sto.isna().sum()

store_id                 0
region_id                0
store_type               0
store_name               0
store_street_address     0
store_city               0
store_state              0
store_country            0
store_phone              1
first_opened_date        0
last_remodel_date       12
total_sqft               0
grocery_sqft             3
dtype: int64

In [139]:
# store_phone: Retained the 1 missing value since the correct phone number could not be determined.
 #last_remodel_date: Retained the 12 missing values because the actual remodel dates could not be reliably inferred.
# grocery_sqft: Filled the 3 missing values with the median to preserve the distribution while reducing the impact of outliers.

sto["grocery_sqft"].fillna(sto["grocery_sqft"].median(), inplace= True)

C:\Users\Ranu Gupta\AppData\Local\Temp\ipykernel_10640\1455060995.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sto["grocery_sqft"].fillna(sto["grocery_sqft"].median(), inplace= True)

In [140]:
sto.isna().sum()

store_id                 0
region_id                0
store_type               0
store_name               0
store_street_address     0
store_city               0
store_state              0
store_country            0
store_phone              1
first_opened_date        0
last_remodel_date       12
total_sqft               0
grocery_sqft             0
dtype: int64

In [141]:
sto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   store_id              24 non-null     int64
 1   region_id             24 non-null     int64
 2   store_type            24 non-null     object
 3   store_name            24 non-null     object
 4   store_street_address  24 non-null     object
 5   store_city            24 non-null     object
 6   store_state           24 non-null     object
 7   store_country         24 non-null     object
 8   store_phone           23 non-null     object
 9   first_opened_date     24 non-null     datetime64[ns]
 10  last_remodel_date     12 non-null     datetime64[ns]
 11  total_sqft            24 non-null     int64
 12  grocery_sqft          24 non-null     float64
dtypes: datetime64[ns](2), float64(1), int64(3), object(7)
memory usage: 2.6+ KB

In [142]:
for col in ["store_id", "region_id"]:
    sto[col] = sto[col].astype(str)

In [143]:
sto.shape

(24, 13)

In [144]:
sto.to_csv("cleaned Stores.csv", index= False)

In [145]:
tr_97 = pd.read_csv(r"C:\Users\Ranu Gupta\OneDrive\Desktop\Project 1- Sales Analytics'\Messy dataset\Transactions_1997.csv")

In [146]:
tr_97.head(5)

  transaction_date   stock_date  product_id  customer_id  store_id  quantity
0       30-07-1997   1997-07-29         667       1188.0         4       3.0
1       1997/08/19   08/22/1997         518        878.0         1       4.0
2       01-08-1997   24-07-1997        1408       9678.0         5       2.0
3       25-12-1997  19 Dec 1997        1426       8903.0        13       2.0
4       1997-09-06   09/02/1997        1548       8283.0         7       2.0

In [147]:
tr_97.describe().round(2)

       product_id  customer_id  store_id  quantity
count    86837.00     82447.00  86837.00  85063.00
mean       734.40      5230.86      8.92      2.79
std        454.93      3064.76      4.96      2.86
min          1.00         2.00      1.00     -3.00
25%        295.00      2427.00      5.00      2.00
50%        703.00      5165.00      9.00      2.00
75%       1139.00      8007.00     13.00      3.00
max       1609.00     10300.00     28.00     96.00

In [148]:
tr_97.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86837 entries, 0 to 86836
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_date  86422 non-null  object
 1   stock_date        85942 non-null  object
 2   product_id        86837 non-null  int64
 3   customer_id       82447 non-null  float64
 4   store_id          86837 non-null  int64
 5   quantity          85063 non-null  float64
dtypes: float64(2), int64(2), object(2)
memory usage: 4.0+ MB

In [149]:
tr_97.shape

(86837, 6)

In [150]:
tr_97["transaction_date"] = smart_parse_dates(tr_97["transaction_date"])
tr_97["stock_date"] = smart_parse_dates(tr_97["stock_date"])

In [151]:
tr_97.head(5)

  transaction_date stock_date  product_id  customer_id  store_id  quantity
0       1997-07-30 1997-07-29         667       1188.0         4       3.0
1       1997-08-19 1997-08-22         518        878.0         1       4.0
2       1997-08-01 1997-07-24        1408       9678.0         5       2.0
3       1997-12-25 1997-12-19        1426       8903.0        13       2.0
4       1997-09-06 1997-09-02        1548       8283.0         7       2.0

In [152]:
tr_97.isna().sum()

transaction_date     415
stock_date           895
product_id             0
customer_id         4390
store_id               0
quantity            1774
dtype: int64

In [153]:
# No missing values were removed from the Transactions table because the affected rows still contain valuable transactional information. Missing values in transaction_date, stock_date, and customer_id were retained since the correct values cannot be reliably inferred, while missing values in quantity were also left unchanged because imputing them could introduce artificial sales data and lead to misleading analysis.

In [154]:
tr_97.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86837 entries, 0 to 86836
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_date  86422 non-null  datetime64[ns]
 1   stock_date        85942 non-null  datetime64[ns]
 2   product_id        86837 non-null  int64
 3   customer_id       82447 non-null  float64
 4   store_id          86837 non-null  int64
 5   quantity          85063 non-null  float64
dtypes: datetime64[ns](2), float64(2), int64(2)
memory usage: 4.0 MB

In [155]:
for col in ["product_id", "store_id"]:
    tr_97[col] = tr_97[col].astype(str)

In [156]:
tr_97.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86837 entries, 0 to 86836
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_date  86422 non-null  datetime64[ns]
 1   stock_date        85942 non-null  datetime64[ns]
 2   product_id        86837 non-null  object
 3   customer_id       82447 non-null  float64
 4   store_id          86837 non-null  object
 5   quantity          85063 non-null  float64
dtypes: datetime64[ns](2), float64(2), object(2)
memory usage: 4.0+ MB

In [157]:
tr_97["customer_id"] = tr_97["customer_id"].astype("Int64").astype("string")

In [158]:
tr_97.to_csv("cleaned Transaction-1997.csv", index = False)

In [159]:
tr_98 = pd.read_csv(r"C:\Users\Ranu Gupta\OneDrive\Desktop\Project 1- Sales Analytics'\Messy dataset\Transactions_1998.csv")

In [160]:
tr_98.head(5)

  transaction_date   stock_date  product_id  customer_id  store_id  quantity
0       05-01-1998  31 Dec 1997         383       1210.0        19       4.0
1       1998/07/18   07/10/1998         312       9678.0         5       5.0
2      06 Dec 1998   26-11-1998         306        348.0        12       2.0
3      04 Nov 1998  03 Nov 1998        1421       4227.0        18       5.0
4      29 Oct 1998   23-10-1998        1172       9262.0        10       3.0

In [161]:
tr_98.shape

(182883, 6)

In [162]:
tr_98.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 182883 entries, 0 to 182882
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_date  181971 non-null  object
 1   stock_date        181043 non-null  object
 2   product_id        182883 non-null  int64
 3   customer_id       173786 non-null  float64
 4   store_id          182883 non-null  int64
 5   quantity          179296 non-null  float64
dtypes: float64(2), int64(2), object(2)
memory usage: 8.4+ MB

In [163]:
tr_98["transaction_date"] = smart_parse_dates(tr_98["transaction_date"])
tr_98["stock_date"] = smart_parse_dates(tr_98["stock_date"])

In [164]:
for col in ["product_id", "store_id"]:
    tr_98[col] = tr_98[col].astype(str)

In [165]:
tr_98.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 182883 entries, 0 to 182882
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_date  181971 non-null  datetime64[ns]
 1   stock_date        181043 non-null  datetime64[ns]
 2   product_id        182883 non-null  object
 3   customer_id       173786 non-null  float64
 4   store_id          182883 non-null  object
 5   quantity          179296 non-null  float64
dtypes: datetime64[ns](2), float64(2), object(2)
memory usage: 8.4+ MB

In [166]:
tr_98["customer_id"] = tr_98["customer_id"].astype("Int64").astype("string")

In [167]:
tr_98.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 182883 entries, 0 to 182882
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_date  181971 non-null  datetime64[ns]
 1   stock_date        181043 non-null  datetime64[ns]
 2   product_id        182883 non-null  object
 3   customer_id       173786 non-null  string
 4   store_id          182883 non-null  object
 5   quantity          179296 non-null  float64
dtypes: datetime64[ns](2), float64(1), object(2), string(1)
memory usage: 8.4+ MB

In [168]:
tr_98.isna().sum()

transaction_date     912
stock_date          1840
product_id             0
customer_id         9097
store_id               0
quantity            3587
dtype: int64

In [169]:
# No missing values were removed from the Transactions tables because the affected rows still contain valuable transactional information. Missing values in transaction_date and  stock_date were retained since the correct values cannot be reliably inferred, while missing values in quantity were also left unchanged because imputing them could introduce artificial sales data and lead to misleading analysis.

In [170]:
tr_98.to_csv("cleaned Transactions-1998.csv", index = False)

In [171]:
# Outliers have not been removed during the data cleaning stage, as their validity can only be assessed in the context of the data distribution and business requirements. They will be identified and treated, if necessary, during the Exploratory Data Analysis (EDA) phase.